name: Flask CI on dev branch

on:
  push:
    branches: [ origin/dev ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: MyPy test
      run: mypy --show-error-codes .
    - name: Test with pytest
      run: py.test tests.py
